version: '2'
services:
  velociraptor:
    container_name: velociraptor
    image: xboarder56/velociraptor
    # build:
    #  context: ./
    #  dockerfile: Dockerfile
    #  args:
    #   VELOX_VERSION: ${VELOX_VERSION:-v0.75.1}
    volumes:
      - ./velociraptor:/velociraptor/:rw
    environment:
      - VELOX_USER=${VELOX_USER}
      - VELOX_PASSWORD=${VELOX_PASSWORD}
      - VELOX_ROLE=${VELOX_ROLE}
      - VELOX_SERVER_URL=${VELOX_SERVER_URL}
      - VELOX_FRONTEND_HOSTNAME=${VELOX_FRONTEND_HOSTNAME}
    ports:
      - "8000:8000"
      - "8001:8001"
      - "8889:8889"
    restart: unless-stopped
